//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlatFileReader3._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class starcite_global_conf
    {
        public long id { get; set; }
        public string fieldName { get; set; }
        public Nullable<int> isRequired { get; set; }
        public string actualValue { get; set; }
        public Nullable<int> isActive { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
    }
}
